#!/usr/bin/env lua

function execute(command)
	local pipe = assert(io.popen(command))
	local result = assert(pipe:read("*a"))
	pipe:close()
	return result
end

function detect_system(config_data)
	for program in pairs(config_data) do
		local result = execute("which " .. program)

		if result and #result > 0 then
			return config_data[program]
		end
	end

	return nil
end

function search_with(search_command, info_command)
	-- fzf configuration. The preview window (showing detailed information
	-- about a package) can be toggled with Ctrl+i
	local fzf = string.format([[
		fzf --multi \
			--ansi \
			--height=90%% \
			--layout=reverse \
			--bind=ctrl-i:toggle-preview \
			--preview-window=bottom:50%% \
			--preview='%s {+1}'
	]], info_command)

	return function(package_name)
		local full_command =
			table.concat({search_command, package_name, "|", fzf}, " ")
		local result = execute(full_command)

		if not result or #result == 0 then
			return nil
		end

		local packages = {}

		for line in result:gmatch("[^\n]+") do
			packages[#packages+1] = line:match("[^ \\t]+")
		end

		print(tr("SelectedPackages", table.concat(packages, ", ")))
		print("")
		return packages
	end
end

function programs(data)
	local commands = detect_system(data)
	if not commands then return end

	local search = search_with(commands.search, commands.details)
	local search_installed = search_with(commands.search_installed, commands.details)

	return {
		["install"] = function(name)
			local packages = search(name)
			if not packages then return end

			os.execute(commands.install .. " " .. table.concat(packages, " "))
		end,

		["details"] = function(name)
			local packages = search(name)
			if not packages then return end

			for _, package in ipairs(packages) do
				local heading = tr("InfoHeading", package)
				print(heading)
				print(string.rep("-", #heading))
				print("")
				assert(os.execute(commands.details .. " " .. package))
				print("")
			end
		end,

		["remove"] = function(name)
			local packages = search_installed(name)
			if not packages then return end

			os.execute(commands.remove .. " " .. table.concat(packages, " "))
		end,

		["no-orphans"] = function()
			if type(commands.no_orphans) == "table" then
				local result = execute(commands.no_orphans[1])

				if result and #result > 0 then
					os.execute(commands.no_orphans[2] .. " " .. result)
				end
			else
				os.execute(commands.no_orphans)
			end
		end,

		["update"] = function()
			os.execute(commands.update)
		end
	}
end

function detect_locale()
	local lang = os.getenv("LANG")
	return lang:match("[^.]+")
end

function translations(data)
	local locale = detect_locale()
	local translation_table = data[locale] or data["en_US"]

	return function(code, ...)
		return string.format(translation_table[code], ...)
	end
end

function config(data)
	return data[1], data[2]
end

program, tr = config {
	programs {
		eopkg = {
			search = "eopkg search",
			search_installed = "eopkg search --installdb",
			details = "eopkg info",
			install = "eopkg install",
			remove = "eopkg remove",
			no_orphans = "eopkg remove-orphans",
			update = "eopkg upgrade"
		},
		apt = {
			search = "apt-cache search",
			search_installed = "dpkg --show --showformat='${Package} ${binary:Sumary}\\n' | grep",
			details = "apt-cache showpkg",
			install = "apt-get install",
			remove = "apt-get remove",
			no_orphans = "apt-get autoremove",
			update = "apt-get update; apt-get upgrade"
		},
		pacman = {
			search = "pacman -Ss",
			search_installed = "pacman -Qs",
			details = "pacman -Si",
			install = "pacman -S",
			remove = "pacman -Rs",
			no_orphans = {"pacman -Qtdq", "pacman -Rns"},
			update = "pacman -Suy"
		}
	},

	translations {
		pt_BR = {
			SelectedPackages = "Pacotes selecionados: %s.",
			InfoHeading = "Pacote %s",
			Unsupported = "Este programa não funciona em seu sistema.",
			UnknownSubcommand = "Subcomando “%s” não reconhecido."
		},
		en_US = {
			SelectedPackages = "Selected packages: %s.",
			InfoHeading = "Package %s",
			Unsupported = "This program doesn't work on your system.",
			UnknownSubcommand = "Unknown subcommand “%s”."
		}
	}
}

if not program then
	print(tr "Unsupported")
	os.exit(1)
end

local subcommand = arg[1]

if not program[subcommand] then
	print(tr("UnknownSubcommand", subcommand))
	os.exit(2)
end

program[subcommand](arg[2])
